### ISSUE TITLE
Generate clean jsx that is easier to comprehend.

### ISSUE THREAD

**Issue by zleman1593** [timbrandin/sideburns#5]
Hi,
Would you be able to create a new repo that performs a similar task where instead of converting everything to the final .js files it converts the html.jsx just to .jsx? This would be great so that I can transition an existing project to .jsx as I learn to write jsx.  Perhaps just a command line node version of the program?   Thanks. :+1:

**Comment by timbrandin** [comment]
I guess that's just down to removing the final babel step.

**Comment by timbrandin** [comment]
Why not clone the repo into your packages folder, and change these lines https://github.com/timbrandin/meteor-react-sideburns/blob/devel/sideburns.js#L179-L210

**Comment by zleman1593** [comment]
I ended up just having the package print out the prebabel strings to files on my desktop. That worked fine, though the output clearly works it looks like it is program generated instead of the way I would actually write jsx code (i.e strange variable names).  Not a big deal. I just originally thought the package would convert the templates to the nice jsx like the examples in the readme. Thanks.

**Comment by timbrandin** [comment]
Ah, yes, that would be an even better solution actually to compile all of it.

**Comment by timbrandin** [comment]
We could do that. :)

**Comment by timbrandin** [comment]
This is something I aim to improve for Meteor 1.2.

**Comment by timbrandin** [comment]
I'm closing this as I haven't heard anything more about this, moving along to support Blaze 1 completely instead.
